//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_EnotsCompany.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleId { get; set; }
        public string Title { get; set; }
        public string ImageArticle { get; set; }
        public string Link { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string StatusArticle { get; set; }
    }
}
