//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_EnotsCompany.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class PurchaseOrderDetail
    {
        public int PurchaseOrderDetailId { get; set; }
        public string PurchaseOrderId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> LineTotal { get; set; }
        public int UnitId { get; set; }

        public virtual Item Item { get; set; }
        public virtual Unit Unit { get; set; }
        [IgnoreDataMember]
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
