//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary_EnotsCompany.DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.Invoices = new HashSet<Invoice>();
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        }

        public string PurchaseOrderId { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<System.DateTime> InquiriedData { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string SupplierId { get; set; }
        public string WholesalerId { get; set; }
        public string Comment { get; set; }
        public string StatusPurchase { get; set; }
        public string ReplyId { get; set; }
        public string StatusInquiry { get; set; }

        [IgnoreDataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual Wholesaler Wholesaler { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
