//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference_ContactPerson
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPerson", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class ContactPerson : object
    {
        
        private int ContactPersonIdField;
        
        private string EmailField;
        
        private string FullnameField;
        
        private string PhoneField;
        
        private string StatusCPField;
        
        private string WholesalerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactPersonId
        {
            get
            {
                return this.ContactPersonIdField;
            }
            set
            {
                this.ContactPersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCP
        {
            get
            {
                return this.StatusCPField;
            }
            set
            {
                this.StatusCPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WholesalerId
        {
            get
            {
                return this.WholesalerIdField;
            }
            set
            {
                this.WholesalerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
        "on")]
    public partial class MyFaultException : object
    {
        
        private string errorCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_ContactPerson.IContactPersonService")]
    public interface IContactPersonService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactPersonService/getAllContactPerson", ReplyAction="http://tempuri.org/IContactPersonService/getAllContactPersonResponse")]
        System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson[]> getAllContactPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactPersonService/findContactPersonbyId", ReplyAction="http://tempuri.org/IContactPersonService/findContactPersonbyIdResponse")]
        System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson> findContactPersonbyIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactPersonService/findContactPersonbyName", ReplyAction="http://tempuri.org/IContactPersonService/findContactPersonbyNameResponse")]
        System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson[]> findContactPersonbyNameAsync(string nameContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactPersonService/findContactPersonbySalerId", ReplyAction="http://tempuri.org/IContactPersonService/findContactPersonbySalerIdResponse")]
        System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson> findContactPersonbySalerIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactPersonService/createContactPerson", ReplyAction="http://tempuri.org/IContactPersonService/createContactPersonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_ContactPerson.MyFaultException), Action="http://tempuri.org/IContactPersonService/createContactPersonMyFaultExceptionFault" +
            "", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> createContactPersonAsync(ServiceReference_ContactPerson.ContactPerson c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactPersonService/updateContactPerson", ReplyAction="http://tempuri.org/IContactPersonService/updateContactPersonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_ContactPerson.MyFaultException), Action="http://tempuri.org/IContactPersonService/updateContactPersonMyFaultExceptionFault" +
            "", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> updateContactPersonAsync(ServiceReference_ContactPerson.ContactPerson c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactPersonService/deleteContactPerson", ReplyAction="http://tempuri.org/IContactPersonService/deleteContactPersonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_ContactPerson.MyFaultException), Action="http://tempuri.org/IContactPersonService/deleteContactPersonMyFaultExceptionFault" +
            "", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> deleteContactPersonAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IContactPersonServiceChannel : ServiceReference_ContactPerson.IContactPersonService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class ContactPersonServiceClient : System.ServiceModel.ClientBase<ServiceReference_ContactPerson.IContactPersonService>, ServiceReference_ContactPerson.IContactPersonService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ContactPersonServiceClient() : 
                base(ContactPersonServiceClient.GetDefaultBinding(), ContactPersonServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IContactPersonService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactPersonServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ContactPersonServiceClient.GetBindingForEndpoint(endpointConfiguration), ContactPersonServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactPersonServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ContactPersonServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactPersonServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ContactPersonServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ContactPersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson[]> getAllContactPersonAsync()
        {
            return base.Channel.getAllContactPersonAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson> findContactPersonbyIdAsync(int id)
        {
            return base.Channel.findContactPersonbyIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson[]> findContactPersonbyNameAsync(string nameContact)
        {
            return base.Channel.findContactPersonbyNameAsync(nameContact);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_ContactPerson.ContactPerson> findContactPersonbySalerIdAsync(string id)
        {
            return base.Channel.findContactPersonbySalerIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> createContactPersonAsync(ServiceReference_ContactPerson.ContactPerson c)
        {
            return base.Channel.createContactPersonAsync(c);
        }
        
        public System.Threading.Tasks.Task<bool> updateContactPersonAsync(ServiceReference_ContactPerson.ContactPerson c)
        {
            return base.Channel.updateContactPersonAsync(c);
        }
        
        public System.Threading.Tasks.Task<bool> deleteContactPersonAsync(int id)
        {
            return base.Channel.deleteContactPersonAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IContactPersonService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IContactPersonService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.107.14.95/IISHosting/EnotsCompany/ContactPersonService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ContactPersonServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IContactPersonService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ContactPersonServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IContactPersonService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IContactPersonService,
        }
    }
}
