//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference_Article
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Article : object
    {
        
        private System.Nullable<System.DateTime> AddDateField;
        
        private int ArticleIdField;
        
        private string ContentField;
        
        private string ImageArticleField;
        
        private string LinkField;
        
        private string StatusArticleField;
        
        private string TitleField;
        
        private System.Nullable<int> ViewCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddDate
        {
            get
            {
                return this.AddDateField;
            }
            set
            {
                this.AddDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArticleId
        {
            get
            {
                return this.ArticleIdField;
            }
            set
            {
                this.ArticleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageArticle
        {
            get
            {
                return this.ImageArticleField;
            }
            set
            {
                this.ImageArticleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this.LinkField;
            }
            set
            {
                this.LinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusArticle
        {
            get
            {
                return this.StatusArticleField;
            }
            set
            {
                this.StatusArticleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ViewCount
        {
            get
            {
                return this.ViewCountField;
            }
            set
            {
                this.ViewCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
        "on")]
    public partial class MyFaultException : object
    {
        
        private string errorCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Article.IArticleService")]
    public interface IArticleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/getAllArticle", ReplyAction="http://tempuri.org/IArticleService/getAllArticleResponse")]
        System.Threading.Tasks.Task<ServiceReference_Article.Article[]> getAllArticleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/findArticlebyDate", ReplyAction="http://tempuri.org/IArticleService/findArticlebyDateResponse")]
        System.Threading.Tasks.Task<ServiceReference_Article.Article[]> findArticlebyDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/findArticlebyID", ReplyAction="http://tempuri.org/IArticleService/findArticlebyIDResponse")]
        System.Threading.Tasks.Task<ServiceReference_Article.Article> findArticlebyIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/createArticle", ReplyAction="http://tempuri.org/IArticleService/createArticleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_Article.MyFaultException), Action="http://tempuri.org/IArticleService/createArticleMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> createArticleAsync(ServiceReference_Article.Article a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/updateArticle", ReplyAction="http://tempuri.org/IArticleService/updateArticleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_Article.MyFaultException), Action="http://tempuri.org/IArticleService/updateArticleMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> updateArticleAsync(ServiceReference_Article.Article a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArticleService/deleteArticle", ReplyAction="http://tempuri.org/IArticleService/deleteArticleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_Article.MyFaultException), Action="http://tempuri.org/IArticleService/deleteArticleMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> deleteArticleAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IArticleServiceChannel : ServiceReference_Article.IArticleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class ArticleServiceClient : System.ServiceModel.ClientBase<ServiceReference_Article.IArticleService>, ServiceReference_Article.IArticleService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ArticleServiceClient() : 
                base(ArticleServiceClient.GetDefaultBinding(), ArticleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IArticleService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ArticleServiceClient.GetBindingForEndpoint(endpointConfiguration), ArticleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArticleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArticleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArticleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference_Article.Article[]> getAllArticleAsync()
        {
            return base.Channel.getAllArticleAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference_Article.Article[]> findArticlebyDateAsync(System.DateTime date)
        {
            return base.Channel.findArticlebyDateAsync(date);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_Article.Article> findArticlebyIDAsync(int id)
        {
            return base.Channel.findArticlebyIDAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> createArticleAsync(ServiceReference_Article.Article a)
        {
            return base.Channel.createArticleAsync(a);
        }
        
        public System.Threading.Tasks.Task<bool> updateArticleAsync(ServiceReference_Article.Article a)
        {
            return base.Channel.updateArticleAsync(a);
        }
        
        public System.Threading.Tasks.Task<bool> deleteArticleAsync(int id)
        {
            return base.Channel.deleteArticleAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IArticleService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IArticleService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.107.14.95/IISHosting/EnotsCompany/ArticleService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ArticleServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IArticleService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ArticleServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IArticleService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IArticleService,
        }
    }
}
