//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference_PurchaseOrder
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrder", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class PurchaseOrder : object
    {
        
        private string CommentField;
        
        private System.Nullable<System.DateTime> InquiriedDataField;
        
        private System.Nullable<System.DateTime> PurchaseOrderDateField;
        
        private ServiceReference_PurchaseOrder.PurchaseOrderDetail[] PurchaseOrderDetailsField;
        
        private string PurchaseOrderIdField;
        
        private System.Nullable<System.DateTime> ReceivedDateField;
        
        private string ReplyIdField;
        
        private string StatusInquiryField;
        
        private string StatusPurchaseField;
        
        private ServiceReference_PurchaseOrder.Supplier SupplierField;
        
        private string SupplierIdField;
        
        private ServiceReference_PurchaseOrder.Wholesaler WholesalerField;
        
        private string WholesalerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InquiriedData
        {
            get
            {
                return this.InquiriedDataField;
            }
            set
            {
                this.InquiriedDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PurchaseOrderDate
        {
            get
            {
                return this.PurchaseOrderDateField;
            }
            set
            {
                this.PurchaseOrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.PurchaseOrderDetail[] PurchaseOrderDetails
        {
            get
            {
                return this.PurchaseOrderDetailsField;
            }
            set
            {
                this.PurchaseOrderDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseOrderId
        {
            get
            {
                return this.PurchaseOrderIdField;
            }
            set
            {
                this.PurchaseOrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceivedDate
        {
            get
            {
                return this.ReceivedDateField;
            }
            set
            {
                this.ReceivedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyId
        {
            get
            {
                return this.ReplyIdField;
            }
            set
            {
                this.ReplyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusInquiry
        {
            get
            {
                return this.StatusInquiryField;
            }
            set
            {
                this.StatusInquiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusPurchase
        {
            get
            {
                return this.StatusPurchaseField;
            }
            set
            {
                this.StatusPurchaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Supplier Supplier
        {
            get
            {
                return this.SupplierField;
            }
            set
            {
                this.SupplierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierId
        {
            get
            {
                return this.SupplierIdField;
            }
            set
            {
                this.SupplierIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Wholesaler Wholesaler
        {
            get
            {
                return this.WholesalerField;
            }
            set
            {
                this.WholesalerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WholesalerId
        {
            get
            {
                return this.WholesalerIdField;
            }
            set
            {
                this.WholesalerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Supplier : object
    {
        
        private string AddressField;
        
        private string AvatarField;
        
        private string BussinessTypeField;
        
        private System.Nullable<int> CategoryIdField;
        
        private string CompanyNameField;
        
        private string CountryField;
        
        private ServiceReference_PurchaseOrder.Country Country1Field;
        
        private System.Nullable<int> CountryIdField;
        
        private string EmailField;
        
        private string MainProductField;
        
        private string NameField;
        
        private string PhoneField;
        
        private string ProvinceField;
        
        private string StatusField;
        
        private string SupplierIdField;
        
        private string TitleField;
        
        private string TotalEmployeesField;
        
        private string WebsiteField;
        
        private System.Nullable<System.DateTime> YearEstablishedField;
        
        private System.Nullable<int> ZipcodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar
        {
            get
            {
                return this.AvatarField;
            }
            set
            {
                this.AvatarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BussinessType
        {
            get
            {
                return this.BussinessTypeField;
            }
            set
            {
                this.BussinessTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Country Country1
        {
            get
            {
                return this.Country1Field;
            }
            set
            {
                this.Country1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainProduct
        {
            get
            {
                return this.MainProductField;
            }
            set
            {
                this.MainProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province
        {
            get
            {
                return this.ProvinceField;
            }
            set
            {
                this.ProvinceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierId
        {
            get
            {
                return this.SupplierIdField;
            }
            set
            {
                this.SupplierIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalEmployees
        {
            get
            {
                return this.TotalEmployeesField;
            }
            set
            {
                this.TotalEmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this.WebsiteField;
            }
            set
            {
                this.WebsiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> YearEstablished
        {
            get
            {
                return this.YearEstablishedField;
            }
            set
            {
                this.YearEstablishedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Zipcode
        {
            get
            {
                return this.ZipcodeField;
            }
            set
            {
                this.ZipcodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wholesaler", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Wholesaler : object
    {
        
        private string AddressWSField;
        
        private System.Nullable<double> AmountField;
        
        private string AvatarField;
        
        private ServiceReference_PurchaseOrder.ContactPerson[] ContactPersonsField;
        
        private ServiceReference_PurchaseOrder.Country CountryField;
        
        private int CountryIdField;
        
        private string EmailField;
        
        private string FullnameField;
        
        private string PhoneField;
        
        private string StatusWSField;
        
        private string WebsiteField;
        
        private string WholesalerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressWS
        {
            get
            {
                return this.AddressWSField;
            }
            set
            {
                this.AddressWSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar
        {
            get
            {
                return this.AvatarField;
            }
            set
            {
                this.AvatarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.ContactPerson[] ContactPersons
        {
            get
            {
                return this.ContactPersonsField;
            }
            set
            {
                this.ContactPersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Country Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusWS
        {
            get
            {
                return this.StatusWSField;
            }
            set
            {
                this.StatusWSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this.WebsiteField;
            }
            set
            {
                this.WebsiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WholesalerId
        {
            get
            {
                return this.WholesalerIdField;
            }
            set
            {
                this.WholesalerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrderDetail", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class PurchaseOrderDetail : object
    {
        
        private System.Nullable<double> DiscountField;
        
        private ServiceReference_PurchaseOrder.Item ItemField;
        
        private int ItemIdField;
        
        private System.Nullable<double> LineTotalField;
        
        private double PriceField;
        
        private int PurchaseOrderDetailIdField;
        
        private string PurchaseOrderIdField;
        
        private int QuantityField;
        
        private System.Nullable<double> TaxField;
        
        private ServiceReference_PurchaseOrder.Unit UnitField;
        
        private int UnitIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Item Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LineTotal
        {
            get
            {
                return this.LineTotalField;
            }
            set
            {
                this.LineTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PurchaseOrderDetailId
        {
            get
            {
                return this.PurchaseOrderDetailIdField;
            }
            set
            {
                this.PurchaseOrderDetailIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseOrderId
        {
            get
            {
                return this.PurchaseOrderIdField;
            }
            set
            {
                this.PurchaseOrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Tax
        {
            get
            {
                return this.TaxField;
            }
            set
            {
                this.TaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Unit Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitId
        {
            get
            {
                return this.UnitIdField;
            }
            set
            {
                this.UnitIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Item : object
    {
        
        private System.DateTime AddedDateField;
        
        private ServiceReference_PurchaseOrder.Category CategoryField;
        
        private int CategoryIdField;
        
        private string DescriptionItemField;
        
        private System.Nullable<double> DiscountField;
        
        private string FAQField;
        
        private string ImageItemField;
        
        private int ItemIdField;
        
        private string ItemNameField;
        
        private int MinQuantityField;
        
        private string MoreImageField;
        
        private string NoteField;
        
        private System.Nullable<int> ParentItemField;
        
        private string PriceField;
        
        private System.Nullable<int> QuantityField;
        
        private string ShippingFeeField;
        
        private string StatusItemField;
        
        private ServiceReference_PurchaseOrder.Supplier SupplierField;
        
        private string SupplierIdField;
        
        private ServiceReference_PurchaseOrder.Unit UnitField;
        
        private int UnitIdField;
        
        private string UnitpriceField;
        
        private string WarrantyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddedDate
        {
            get
            {
                return this.AddedDateField;
            }
            set
            {
                this.AddedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Category Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionItem
        {
            get
            {
                return this.DescriptionItemField;
            }
            set
            {
                this.DescriptionItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAQ
        {
            get
            {
                return this.FAQField;
            }
            set
            {
                this.FAQField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageItem
        {
            get
            {
                return this.ImageItemField;
            }
            set
            {
                this.ImageItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName
        {
            get
            {
                return this.ItemNameField;
            }
            set
            {
                this.ItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinQuantity
        {
            get
            {
                return this.MinQuantityField;
            }
            set
            {
                this.MinQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoreImage
        {
            get
            {
                return this.MoreImageField;
            }
            set
            {
                this.MoreImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentItem
        {
            get
            {
                return this.ParentItemField;
            }
            set
            {
                this.ParentItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShippingFee
        {
            get
            {
                return this.ShippingFeeField;
            }
            set
            {
                this.ShippingFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusItem
        {
            get
            {
                return this.StatusItemField;
            }
            set
            {
                this.StatusItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Supplier Supplier
        {
            get
            {
                return this.SupplierField;
            }
            set
            {
                this.SupplierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierId
        {
            get
            {
                return this.SupplierIdField;
            }
            set
            {
                this.SupplierIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_PurchaseOrder.Unit Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitId
        {
            get
            {
                return this.UnitIdField;
            }
            set
            {
                this.UnitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unitprice
        {
            get
            {
                return this.UnitpriceField;
            }
            set
            {
                this.UnitpriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warranty
        {
            get
            {
                return this.WarrantyField;
            }
            set
            {
                this.WarrantyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unit", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Unit : object
    {
        
        private int UnitIdField;
        
        private string UnitNameField;
        
        private string UnitStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnitId
        {
            get
            {
                return this.UnitIdField;
            }
            set
            {
                this.UnitIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitName
        {
            get
            {
                return this.UnitNameField;
            }
            set
            {
                this.UnitNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitStatus
        {
            get
            {
                return this.UnitStatusField;
            }
            set
            {
                this.UnitStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Category : object
    {
        
        private int CategoryIdField;
        
        private string CategoryNameField;
        
        private string ImageCateField;
        
        private System.Nullable<int> ParentIdField;
        
        private string StatusCateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageCate
        {
            get
            {
                return this.ImageCateField;
            }
            set
            {
                this.ImageCateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId
        {
            get
            {
                return this.ParentIdField;
            }
            set
            {
                this.ParentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCate
        {
            get
            {
                return this.StatusCateField;
            }
            set
            {
                this.StatusCateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Country : object
    {
        
        private string CommonNameField;
        
        private string CountryCodeField;
        
        private int CountryIdField;
        
        private string StatusCountryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommonName
        {
            get
            {
                return this.CommonNameField;
            }
            set
            {
                this.CommonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCountry
        {
            get
            {
                return this.StatusCountryField;
            }
            set
            {
                this.StatusCountryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPerson", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class ContactPerson : object
    {
        
        private int ContactPersonIdField;
        
        private string EmailField;
        
        private string FullnameField;
        
        private string PhoneField;
        
        private string StatusCPField;
        
        private string WholesalerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactPersonId
        {
            get
            {
                return this.ContactPersonIdField;
            }
            set
            {
                this.ContactPersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCP
        {
            get
            {
                return this.StatusCPField;
            }
            set
            {
                this.StatusCPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WholesalerId
        {
            get
            {
                return this.WholesalerIdField;
            }
            set
            {
                this.WholesalerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
        "on")]
    public partial class MyFaultException : object
    {
        
        private string errorCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_PurchaseOrder.IPurchaseOrderService")]
    public interface IPurchaseOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/getAllPurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/getAllPurchaseOrderResponse")]
        System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder[]> getAllPurchaseOrderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderById", ReplyAction="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder> findPurchaseOrderByIdAsync(string porderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderByWSId", ReplyAction="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderByWSIdResponse")]
        System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder[]> findPurchaseOrderByWSIdAsync(string wsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/getPurchaseOrderId", ReplyAction="http://tempuri.org/IPurchaseOrderService/getPurchaseOrderIdResponse")]
        System.Threading.Tasks.Task<string> getPurchaseOrderIdAsync(string wholesalerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderDetailbypId", ReplyAction="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderDetailbypIdResponse")]
        System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrderDetail[]> findPurchaseOrderDetailbypIdAsync(string purchaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderDetailsById", ReplyAction="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderDetailsByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrderDetail> findPurchaseOrderDetailsByIdAsync(int pdetailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/updatePurchaseOrderDetails", ReplyAction="http://tempuri.org/IPurchaseOrderService/updatePurchaseOrderDetailsResponse")]
        System.Threading.Tasks.Task<bool> updatePurchaseOrderDetailsAsync(ServiceReference_PurchaseOrder.PurchaseOrderDetail pdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderByOdDate", ReplyAction="http://tempuri.org/IPurchaseOrderService/findPurchaseOrderByOdDateResponse")]
        System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder[]> findPurchaseOrderByOdDateAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/createPurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/createPurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_PurchaseOrder.MyFaultException), Action="http://tempuri.org/IPurchaseOrderService/createPurchaseOrderMyFaultExceptionFault" +
            "", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> createPurchaseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder pOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/updatePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/updatePurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_PurchaseOrder.MyFaultException), Action="http://tempuri.org/IPurchaseOrderService/updatePurchaseOrderMyFaultExceptionFault" +
            "", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> updatePurchaseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder pOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/deletePurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/deletePurchaseOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_PurchaseOrder.MyFaultException), Action="http://tempuri.org/IPurchaseOrderService/deletePurchaseOrderMyFaultExceptionFault" +
            "", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> deletePurchaseOrderAsync(string porderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/tranPurcharseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/tranPurcharseOrderResponse")]
        System.Threading.Tasks.Task<bool> tranPurcharseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder purchase, ServiceReference_PurchaseOrder.PurchaseOrderDetail purchasedt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseOrderService/tranUpdatePurcharseOrder", ReplyAction="http://tempuri.org/IPurchaseOrderService/tranUpdatePurcharseOrderResponse")]
        System.Threading.Tasks.Task<bool> tranUpdatePurcharseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder purchase, ServiceReference_PurchaseOrder.PurchaseOrderDetail purchasedt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IPurchaseOrderServiceChannel : ServiceReference_PurchaseOrder.IPurchaseOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class PurchaseOrderServiceClient : System.ServiceModel.ClientBase<ServiceReference_PurchaseOrder.IPurchaseOrderService>, ServiceReference_PurchaseOrder.IPurchaseOrderService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PurchaseOrderServiceClient() : 
                base(PurchaseOrderServiceClient.GetDefaultBinding(), PurchaseOrderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IPurchaseOrderService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PurchaseOrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PurchaseOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), PurchaseOrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PurchaseOrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PurchaseOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PurchaseOrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PurchaseOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PurchaseOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder[]> getAllPurchaseOrderAsync()
        {
            return base.Channel.getAllPurchaseOrderAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder> findPurchaseOrderByIdAsync(string porderId)
        {
            return base.Channel.findPurchaseOrderByIdAsync(porderId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder[]> findPurchaseOrderByWSIdAsync(string wsId)
        {
            return base.Channel.findPurchaseOrderByWSIdAsync(wsId);
        }
        
        public System.Threading.Tasks.Task<string> getPurchaseOrderIdAsync(string wholesalerId)
        {
            return base.Channel.getPurchaseOrderIdAsync(wholesalerId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrderDetail[]> findPurchaseOrderDetailbypIdAsync(string purchaseId)
        {
            return base.Channel.findPurchaseOrderDetailbypIdAsync(purchaseId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrderDetail> findPurchaseOrderDetailsByIdAsync(int pdetailId)
        {
            return base.Channel.findPurchaseOrderDetailsByIdAsync(pdetailId);
        }
        
        public System.Threading.Tasks.Task<bool> updatePurchaseOrderDetailsAsync(ServiceReference_PurchaseOrder.PurchaseOrderDetail pdetail)
        {
            return base.Channel.updatePurchaseOrderDetailsAsync(pdetail);
        }
        
        public System.Threading.Tasks.Task<ServiceReference_PurchaseOrder.PurchaseOrder[]> findPurchaseOrderByOdDateAsync(System.DateTime date)
        {
            return base.Channel.findPurchaseOrderByOdDateAsync(date);
        }
        
        public System.Threading.Tasks.Task<bool> createPurchaseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder pOrder)
        {
            return base.Channel.createPurchaseOrderAsync(pOrder);
        }
        
        public System.Threading.Tasks.Task<bool> updatePurchaseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder pOrder)
        {
            return base.Channel.updatePurchaseOrderAsync(pOrder);
        }
        
        public System.Threading.Tasks.Task<bool> deletePurchaseOrderAsync(string porderId)
        {
            return base.Channel.deletePurchaseOrderAsync(porderId);
        }
        
        public System.Threading.Tasks.Task<bool> tranPurcharseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder purchase, ServiceReference_PurchaseOrder.PurchaseOrderDetail purchasedt)
        {
            return base.Channel.tranPurcharseOrderAsync(purchase, purchasedt);
        }
        
        public System.Threading.Tasks.Task<bool> tranUpdatePurcharseOrderAsync(ServiceReference_PurchaseOrder.PurchaseOrder purchase, ServiceReference_PurchaseOrder.PurchaseOrderDetail purchasedt)
        {
            return base.Channel.tranUpdatePurcharseOrderAsync(purchase, purchasedt);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IPurchaseOrderService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IPurchaseOrderService))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("http://10.107.14.95/IISHosting/EnotsCompany/PurchaseOrderService.svc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PurchaseOrderServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IPurchaseOrderService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PurchaseOrderServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IPurchaseOrderService);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IPurchaseOrderService,
        }
    }
}
