//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference_Wholesaler
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wholesaler", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Wholesaler : object
    {
        
        private string AddressWSField;
        
        private System.Nullable<double> AmountField;
        
        private string AvatarField;
        
        private ServiceReference_Wholesaler.ContactPerson[] ContactPersonsField;
        
        private ServiceReference_Wholesaler.Country CountryField;
        
        private int CountryIdField;
        
        private string EmailField;
        
        private string FullnameField;
        
        private string PhoneField;
        
        private string StatusWSField;
        
        private string WebsiteField;
        
        private string WholesalerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressWS
        {
            get
            {
                return this.AddressWSField;
            }
            set
            {
                this.AddressWSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar
        {
            get
            {
                return this.AvatarField;
            }
            set
            {
                this.AvatarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_Wholesaler.ContactPerson[] ContactPersons
        {
            get
            {
                return this.ContactPersonsField;
            }
            set
            {
                this.ContactPersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference_Wholesaler.Country Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusWS
        {
            get
            {
                return this.StatusWSField;
            }
            set
            {
                this.StatusWSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website
        {
            get
            {
                return this.WebsiteField;
            }
            set
            {
                this.WebsiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WholesalerId
        {
            get
            {
                return this.WholesalerIdField;
            }
            set
            {
                this.WholesalerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class Country : object
    {
        
        private string CommonNameField;
        
        private string CountryCodeField;
        
        private int CountryIdField;
        
        private string StatusCountryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommonName
        {
            get
            {
                return this.CommonNameField;
            }
            set
            {
                this.CommonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryId
        {
            get
            {
                return this.CountryIdField;
            }
            set
            {
                this.CountryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCountry
        {
            get
            {
                return this.StatusCountryField;
            }
            set
            {
                this.StatusCountryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPerson", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.DAL")]
    public partial class ContactPerson : object
    {
        
        private int ContactPersonIdField;
        
        private string EmailField;
        
        private string FullnameField;
        
        private string PhoneField;
        
        private string StatusCPField;
        
        private string WholesalerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactPersonId
        {
            get
            {
                return this.ContactPersonIdField;
            }
            set
            {
                this.ContactPersonIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCP
        {
            get
            {
                return this.StatusCPField;
            }
            set
            {
                this.StatusCPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WholesalerId
        {
            get
            {
                return this.WholesalerIdField;
            }
            set
            {
                this.WholesalerIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
        "on")]
    public partial class MyFaultException : object
    {
        
        private string errorCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_Wholesaler.IWholesalerService")]
    public interface IWholesalerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWholesalerService/getAllWholesaler", ReplyAction="http://tempuri.org/IWholesalerService/getAllWholesalerResponse")]
        System.Threading.Tasks.Task<ServiceReference_Wholesaler.Wholesaler[]> getAllWholesalerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWholesalerService/findWholesalerById", ReplyAction="http://tempuri.org/IWholesalerService/findWholesalerByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference_Wholesaler.Wholesaler> findWholesalerByIdAsync(string wId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWholesalerService/createWholesaler", ReplyAction="http://tempuri.org/IWholesalerService/createWholesalerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_Wholesaler.MyFaultException), Action="http://tempuri.org/IWholesalerService/createWholesalerMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> createWholesalerAsync(ServiceReference_Wholesaler.Wholesaler wholesaler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWholesalerService/updateWholesaler", ReplyAction="http://tempuri.org/IWholesalerService/updateWholesalerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_Wholesaler.MyFaultException), Action="http://tempuri.org/IWholesalerService/updateWholesalerMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> updateWholesalerAsync(ServiceReference_Wholesaler.Wholesaler wholesaler);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWholesalerService/deleteWholesaler", ReplyAction="http://tempuri.org/IWholesalerService/deleteWholesalerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference_Wholesaler.MyFaultException), Action="http://tempuri.org/IWholesalerService/deleteWholesalerMyFaultExceptionFault", Name="MyFaultException", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary_EnotsCompany.My_Excepti" +
            "on")]
        System.Threading.Tasks.Task<bool> deleteWholesalerAsync(string wId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWholesalerService/getWholesalerId", ReplyAction="http://tempuri.org/IWholesalerService/getWholesalerIdResponse")]
        System.Threading.Tasks.Task<string> getWholesalerIdAsync(int countryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IWholesalerServiceChannel : ServiceReference_Wholesaler.IWholesalerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class WholesalerServiceClient : System.ServiceModel.ClientBase<ServiceReference_Wholesaler.IWholesalerService>, ServiceReference_Wholesaler.IWholesalerService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WholesalerServiceClient() : 
                base(WholesalerServiceClient.GetDefaultBinding(), WholesalerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWholesalerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WholesalerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WholesalerServiceClient.GetBindingForEndpoint(endpointConfiguration), WholesalerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WholesalerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WholesalerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WholesalerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WholesalerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WholesalerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference_Wholesaler.Wholesaler[]> getAllWholesalerAsync()
        {
            return base.Channel.getAllWholesalerAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference_Wholesaler.Wholesaler> findWholesalerByIdAsync(string wId)
        {
            return base.Channel.findWholesalerByIdAsync(wId);
        }
        
        public System.Threading.Tasks.Task<bool> createWholesalerAsync(ServiceReference_Wholesaler.Wholesaler wholesaler)
        {
            return base.Channel.createWholesalerAsync(wholesaler);
        }
        
        public System.Threading.Tasks.Task<bool> updateWholesalerAsync(ServiceReference_Wholesaler.Wholesaler wholesaler)
        {
            return base.Channel.updateWholesalerAsync(wholesaler);
        }
        
        public System.Threading.Tasks.Task<bool> deleteWholesalerAsync(string wId)
        {
            return base.Channel.deleteWholesalerAsync(wId);
        }
        
        public System.Threading.Tasks.Task<string> getWholesalerIdAsync(int countryId)
        {
            return base.Channel.getWholesalerIdAsync(countryId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWholesalerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWholesalerService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.107.14.95/IISHosting/EnotsCompany/WholesalerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WholesalerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWholesalerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WholesalerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWholesalerService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWholesalerService,
        }
    }
}
